# Generated by Django 4.2.9 on 2024-01-31 18:17

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="NotionIntegration",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "workspace",
                    models.CharField(
                        default="", help_text="The workspace", max_length=9000
                    ),
                ),
                (
                    "notion_token",
                    models.CharField(help_text="The notion token", max_length=9000),
                ),
                (
                    "user",
                    models.ForeignKey(
                        help_text="The user that created the dataset",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="omero_user",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
        migrations.AddConstraint(
            model_name="notionintegration",
            constraint=models.UniqueConstraint(
                fields=("user", "workspace"), name="Unique user and workspace"
            ),
        ),
    ]
